#!/usr/bin/env python
import os,sys
try:
	import tkinter as tk
except:
	import Tkinter as tk
import tkFileDialog
def en(text,pw,ty):
	ty=str(ty)
	if ty!="0" and ty!="1":
		ty="0"
	p=0 if ty=="0" else ""
	for a in pw:
		p+=ord(a) if ty=="0" else str(ord(a))
	pw=int(p)
	l=[]
	for a in text:
		l.append(str(ord(a)+pw))
	text=";".join(l)
	return text
def de(text,pw,ty):
	ty=str(ty)
	if ty!="0" and ty!="1":
		ty="0"
	p=0 if ty=="0" else ""
	for a in pw:
		p+=ord(a) if ty=="0" else str(ord(a))
	pw=int(p)
	l=[]
	text=text.split(";")
	if text[-1]=="":
		text.pop(-1)
	for a in text:
		l.append(chr(int(a)-pw))
	text="".join(l)
	return text
def ch():
	global f
	global fc
	global filename
	f=tkFileDialog.askopenfilename()
	filename=f.split("/")[-1]
	op=open(f,"r")
	fc=op.read()
	op.close()
	fn["text"]=filename
	relf()
def relf():
	global txtt
	op=open(f,"r")
	content=op.read()
	op.close()
	txtt.delete("1.0",tk.END)
	txtt.insert(tk.INSERT,content)
	status["text"]=""
def savef():
	global txtt
	op=open(f,"w")
	op.write(txtt.get("1.0",'end-1c'))
	op.close()
	status["text"]="Saved as '"+f+"'"
def ed(e):
	global ende
	global tipo
	global txtt
	status["text"]=""
	if e.widget.get()!="":
		try:
			t=txtt.get("1.0",'end-1c')
			if tipo.get()=="":
				tp=0
			else:
				tp=tipo.get()
			if ende.get()==10:
				dt=en(t,e.widget.get(),tp)
			else:
				dt=de(t,e.widget.get(),tp)
			txtt.delete("1.0",tk.END)
			txtt.insert(tk.INSERT,dt)
		except Exception as e:
			if str(e).startswith("invalid literal for int()"):
				status["text"]="Invalid password."
			else:
				status["text"]="Error: "+str(e)
global w0
w=tk.Tk()
global f
f=tkFileDialog.askopenfilename()
global filename
filename=f.split("/")[-1]
fo=open(f,"r")
global fc
fc=fo.read()
fo.close()
w.title(filename+" - D3cTXTEditor")
head=tk.Frame(w)
head.pack()
fn=tk.Button(head,text=filename,command=ch)
fn.pack(side=tk.LEFT)
pt=tk.Label(head,text="Password (press <ENTER>):")
pt.pack(side=tk.LEFT)
global pi
pi=tk.Entry(head,bd=0.5,show="*")
pi.pack(side=tk.LEFT)
pi.focus_set()
head2=tk.Frame(w)
head2.pack()
head2l=tk.Frame(head2)
head2l.pack(side=tk.LEFT)
head2c=tk.Frame(head2)
head2c.pack(side=tk.LEFT)
head2r=tk.Frame(head2)
head2r.pack(side=tk.LEFT)
global ende
ende=tk.IntVar()
ed1=tk.Radiobutton(head2c,text="Encrypt",variable=ende,value=10)
ed2=tk.Radiobutton(head2c,text="Decrypt",variable=ende,value=11)
ed1.pack()
ed2.pack()
global tipo
tipo=tk.IntVar()
tp1=tk.Radiobutton(head2r,text="Short",variable=tipo,value=0)
tp2=tk.Radiobutton(head2r,text="Long",variable=tipo,value=1)
tp1.pack()
tp2.pack()
global txtt
txtt=tk.Text(w)
txtt.insert(tk.INSERT,fc)
txtt.pack()
status=tk.Label(w,text="")
status.pack(side=tk.BOTTOM)
rf=tk.Button(head2l,text="Reload file",command=relf)
rf.pack(side=tk.LEFT)
sf=tk.Button(head2l,text="Save file",command=savef)
sf.pack(side=tk.LEFT)
pi.bind("<Return>",ed)
w.mainloop()